# Minimal netlify.toml
# We no longer define a global [build] block here
# so each Netlify project can set its own Publish directory (jasmine, taxoffice, 4features)

# Example: if you want redirects on all projects, you can still define them here:
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# You can later add per-project context if needed:
# [context.production]
#   command = ""
#   publish = "jasmine"

# [context.taxoffice]
#   command = ""
#   publish = "taxoffice"

# [context.4features]
#   command = ""
#   publish = "4features"
